import { noticeMetrics as n } from "../../desktop/src/notice-contract.js";
import { StyleSheet } from "react-native";
import { geometry as g } from "./design-tokens.js";
import { palettes } from "./palette.js";
export { palettes };
export function styles(
  c,
  wide = false,
  compact = false,
  fontScale = 1,
  textScale = 1,
) {
  const controlHeight = Math.max(
    g.touchControlHeight,
    Math.ceil(26 * fontScale * textScale + 18),
  );
  const rules = {
    scaffoldRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: c.divider,
      borderRadius: g.cardRadius,
      backgroundColor: c.surface,
    },
    scaffoldDashed: { borderStyle: "dashed", backgroundColor: c.paper },
    scaffoldMark: {
      width: 40,
      height: 40,
      borderRadius: g.controlRadius,
      backgroundColor: c.hover,
    },
    scaffoldDot: { width: 10, height: 10, borderRadius: 5 },
    scaffoldCopy: { flex: 1, gap: 8 },
    scaffoldLine: {
      height: 12,
      borderRadius: g.segmentRadius,
      backgroundColor: c.hover,
      opacity: 0.65,
    },
    scaffoldTitle: { height: 16, width: "60%" },
    scaffoldLong: { width: "85%" },
    scaffoldShort: { width: 40 },

    timeline: { gap: 20 },
    timelineStatus: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      minHeight: 24,
    },
    pendingUploads: {
      padding: 12,
      gap: 12,
      borderWidth: 1,
      borderColor: c.divider,
      borderRadius: g.cardRadius,
      backgroundColor: c.surface,
    },
    pendingUploadStrip: { gap: 8 },
    timelineGroup: { gap: 8 },
    timelineMonth: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchRowFont,
      lineHeight: g.touchRowLine,
      color: c.ink,
    },
    photoGrid: { flexDirection: "row", flexWrap: "wrap" },
    photoTile: {
      borderRadius: 4,
      overflow: "hidden",
      backgroundColor: c.surface,
    },
    photoBadge: {
      position: "absolute",
      bottom: 4,
      right: 4,
      padding: 3,
      borderRadius: g.pillRadius,
      backgroundColor: "rgba(0,0,0,0.55)",
    },
    viewerRoot: { flex: 1, backgroundColor: "#000" },
    viewerPage: {
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      gap: 12,
      padding: 24,
    },
    viewerPoster: { position: "absolute", opacity: 0.6 },
    viewerPlay: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: "rgba(255,255,255,0.18)",
      alignItems: "center",
      justifyContent: "center",
    },
    viewerChrome: {
      position: "absolute",
      left: 0,
      right: 0,
      paddingHorizontal: 12,
      backgroundColor: "rgba(0,0,0,0.6)",
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    viewerTop: { top: 0, paddingBottom: 8 },
    viewerTitle: {
      color: "#fff",
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchBodyFont,
      lineHeight: g.touchBodyLine,
    },
    viewerCaption: {
      color: "rgba(255,255,255,0.72)",
      fontFamily: "InstrumentSans_400Regular",
      fontSize: g.touchCaptionFont,
      lineHeight: g.touchCaptionLine,
      textAlign: "center",
    },
    infoPanel: {
      position: "absolute",
      backgroundColor: c.paper,
      overflow: "hidden",
    },
    infoSheet: {
      left: 0,
      right: 0,
      bottom: 0,
      maxHeight: "72%",
      borderTopLeftRadius: 14,
      borderTopRightRadius: 14,
    },
    infoSide: {
      top: 0,
      bottom: 0,
      right: 0,
      width: 360,
      borderLeftWidth: 1,
      borderColor: c.line,
    },
    infoBody: { padding: 16, gap: 24 },
    infoIdentity: { gap: 8, paddingHorizontal: 4 },
    infoFilename: {
      color: c.ink,
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchBodyFont,
      lineHeight: g.touchBodyLine,
    },
    infoCard: {
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: g.controlRadius,
      padding: 16,
      gap: 20,
    },
    infoValues: { gap: 4 },
    infoLabel: {
      color: c.mute,
      fontFamily: "InstrumentSans_400Regular",
      fontSize: g.touchCaptionFont,
      lineHeight: g.touchCaptionLine,
    },
    infoMetricValue: {
      color: c.ink,
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchBodyFont,
      lineHeight: g.touchBodyLine,
    },
    infoLink: {
      color: c.accent,
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchBodyFont,
      lineHeight: g.touchBodyLine,
    },
    infoRow: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
    infoMetrics: {
      flexDirection: "row",
      flexWrap: "wrap",
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: g.controlRadius,
      backgroundColor: c.surface,
    },
    infoMetric: { width: "50%", padding: 12, gap: 4 },
    infoFooter: {
      flexDirection: "row",
      padding: 16,
      borderTopWidth: 1,
      borderColor: c.divider,
    },
    viewerIconButton: {
      width: g.touchHeight,
      height: g.touchHeight,
      alignItems: "center",
      justifyContent: "center",
    },
    galleryGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    galleryTile: {
      width: "23%",
      aspectRatio: 1,
      borderRadius: g.controlRadius,
      overflow: "hidden",
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.line,
    },
    galleryImage: { width: "100%", height: "100%" },
    galleryPlaceholder: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      padding: 8,
      gap: 8,
    },
    root: { flex: 1, backgroundColor: c.paper },
    shell: { flexDirection: "row" },
    setup: { maxWidth: 480, paddingHorizontal: 24, paddingTop: 32, gap: 24 },
    displayTitle: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: 36,
      lineHeight: 38,
      letterSpacing: -1.4,
      color: c.ink,
    },
    emphasis: { fontStyle: "italic", color: c.accent },
    featureRow: { flexDirection: "row", alignItems: "flex-start", gap: 16 },
    tileLarge: { width: g.touchHeight, height: g.touchHeight },
    selectedCard: { borderColor: c.accent },
    selectionCheck: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: c.accent,
      alignItems: "center",
      justifyContent: "center",
    },
    inputShell: {
      height: controlHeight,
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      gap: 12,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: g.controlRadius,
      backgroundColor: c.surface,
    },
    inputEmbedded: {
      height: controlHeight - 2,
      minHeight: 0,
      flex: 1,
      minWidth: 0,
      borderWidth: 0,
      paddingHorizontal: 0,
    },
    codeControl: { position: "relative" },
    codeCells: { flexDirection: "row", alignItems: "center", gap: 6 },
    codeCell: {
      flex: 1,
      minHeight: 54,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: g.controlRadius,
      backgroundColor: c.surface,
      alignItems: "center",
      justifyContent: "center",
    },
    codeDigit: {
      fontFamily: "FragmentMono_400Regular",
      fontSize: 24,
      color: c.ink,
    },
    codeSeparator: { fontSize: 24, color: c.line },
    codeCapture: {
      ...StyleSheet.absoluteFill,
      opacity: 0.02,
      color: "transparent",
      fontSize: 24,
    },
    controlFocused: {
      borderColor: c.accent,
      outlineWidth: 3,
      outlineColor: c.tint,
      outlineStyle: "solid",
    },
    stepIndicator: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
    },
    stepDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: c.line },
    stepDotActive: { width: 20, backgroundColor: c.accent },
    centeredRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
    },
    navigation: {
      width: compact ? 64 : 200,
      backgroundColor: c.side,
      borderRightWidth: 1,
      borderColor: c.divider,
      padding: compact ? 10 : 12,
      paddingTop: g.workspaceInset,
      gap: 8,
    },
    brand: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      minHeight: controlHeight,
    },
    identity: {
      flexDirection: "row",
      alignItems: "center",
      minHeight: 36,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.divider,
      borderRadius: g.controlRadius,
      paddingHorizontal: 8,
      gap: 8,
    },
    tileAvailable: { backgroundColor: c.hover },
    segments: {
      alignSelf: wide ? "flex-start" : "stretch",
      flexDirection: "row",
      backgroundColor: c.hover,
      borderRadius: g.controlRadius,
      padding: 3,
      gap: 2,
    },
    segment: {
      flex: wide ? 0 : 1,
      paddingHorizontal: wide ? 12 : 0,
      minHeight: 38,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: g.segmentRadius,
    },
    segmentText: { color: c.soft },
    segmentTextSelected: { color: c.ink },
    segmentSelected: {
      backgroundColor: c.surface,
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 2,
      elevation: 1,
    },
    navItem: {
      minHeight: g.touchHeight,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 12,
      borderRadius: g.controlRadius,
    },
    compactNav: { paddingHorizontal: 0, justifyContent: "center" },
    compactBrand: { justifyContent: "center" },
    navLabel: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchCaptionFont,
      lineHeight: g.touchControlLine,
      color: c.ink,
    },
    navSelected: { backgroundColor: c.tint },
    navFooter: { marginTop: "auto", padding: 12, gap: 6 },
    folderRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      minHeight: g.touchControlHeight + 2 * g.listRowPaddingY + 2,
      paddingVertical: g.listRowPaddingY,
      paddingHorizontal: g.listRowPaddingX,
      borderRadius: g.controlRadius,
    },
    groupedFolderRow: { backgroundColor: c.surface, borderRadius: 0 },
    actionRow: {
      flexDirection: "row",
      alignItems: "center",
      minHeight: 52,
      paddingVertical: 12,
      paddingHorizontal: 16,
      gap: 12,
    },
    deletedFile: { textDecorationLine: "line-through" },
    conflictChoice: { borderWidth: 2, borderColor: c.divider, gap: 8 },
    conflictChoiceSelected: { borderColor: c.accent },
    actionGroup: { overflow: "hidden" },
    destructiveActionGroup: { borderTopWidth: 1, borderColor: c.divider },
    sheetHandle: {
      width: 36,
      height: 5,
      borderRadius: 3,
      backgroundColor: c.line,
      alignSelf: "center",
      marginTop: 12,
    },
    approvalTitle: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchTitleFont,
      lineHeight: g.touchTitleLine,
      color: c.ink,
    },
    centerText: { textAlign: "center" },
    requestReference: {
      borderWidth: 1,
      borderStyle: "dashed",
      borderColor: c.line,
      borderRadius: g.cardRadius,
      padding: g.sectionGap,
      gap: g.listItemGap,
      marginVertical: 8,
    },
    requestNumber: {
      fontFamily: "FragmentMono_400Regular",
      fontSize: g.approvalReferenceFont,
      lineHeight: g.touchControlHeight,
      letterSpacing: g.referenceTracking,
      textAlign: "center",
      color: c.ink,
    },
    requestSeparator: { color: c.line },
    approvalRow: {
      flexDirection: "row",
      alignItems: "center",
      padding: g.listRowPaddingX,
      gap: g.listRowPaddingY,
    },
    approvalRowBorder: { borderTopWidth: 1, borderColor: c.divider },
    approvalValue: { flex: 1, textAlign: "right", fontSize: g.touchBodyFont },
    sheetHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingHorizontal: wide ? 24 : 16,
      paddingTop: 12,
    },
    iconButton: {
      width: g.touchControlHeight,
      height: g.touchControlHeight,
      paddingHorizontal: 0,
      paddingVertical: 0,
    },
    smallButton: {
      minHeight: g.buttonSmallHeight,
      paddingVertical: 4,
      paddingHorizontal: 10,
    },
    smallIconButton: {
      width: g.buttonSmallHeight,
      height: g.buttonSmallHeight,
      paddingHorizontal: 0,
      paddingVertical: 0,
    },
    detailTile: {
      width: g.detailTile,
      height: g.detailTile,
      borderRadius: g.cardRadius,
    },
    badgeWarning: { backgroundColor: c.warningBg },
    badgeWarningText: { color: c.warning },
    badgeError: { backgroundColor: c.dangerBg },
    badgeNeutral: { backgroundColor: c.hover },
    badgeBusy: { backgroundColor: "transparent" },
    badgeNeutralText: { color: c.soft },
    noticeDock: {
      position: "absolute",
      left: n.inset,
      right: n.inset,
      alignItems: "center",
    },
    noticeStackScroll: { width: "100%", maxWidth: n.width, flexGrow: 0 },
    noticeStack: { gap: n.gap },
    noticeCard: {
      backgroundColor: c.noticeSurface,
      borderWidth: 1,
      borderColor: c.divider,
      borderRadius: n.radius,
      overflow: "hidden",
      shadowColor: "#000",
      shadowOpacity: 0.14,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    noticeInfo: {
      backgroundColor: c.noticeInfoBg,
      borderColor: c.noticeInfoBg,
    },
    noticeMain: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: n.gap,
      padding: n.padding,
    },
    noticeTitle: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: n.title,
      lineHeight: n.line,
      color: c.ink,
    },
    noticeText: {
      fontFamily: "InstrumentSans_400Regular",
      fontSize: n.body,
      lineHeight: n.line,
      color: c.soft,
      marginTop: 3,
    },
    noticeInfoText: { color: c.noticeInfoFg },
    noticeInfoLink: { color: c.noticeInfoLink },
    noticeMuted: { color: c.mute },
    noticeActions: {
      flexDirection: "row",
      gap: n.gap,
      flexWrap: "wrap",
      marginTop: 4,
    },
    noticeLink: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: n.body,
      lineHeight: n.line,
      color: c.noticeLink,
    },
    noticeLinkTarget: { minHeight: g.touchHeight, justifyContent: "center" },
    noticeClose: {
      width: 16,
      height: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    noticeDetails: {
      backgroundColor: c.paper,
      borderTopWidth: 1,
      borderColor: c.divider,
    },
    noticeDetailsHead: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: n.padding,
    },
    noticeDetailsToggle: {
      flex: 1,
      flexDirection: "row",
      gap: 8,
      minHeight: g.touchHeight,
      alignItems: "center",
    },
    noticeDetailsLabel: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: 13,
      color: c.soft,
    },
    noticeTraceScroll: { maxHeight: 180 },
    noticeTrace: {
      fontFamily: "FragmentMono_400Regular",
      fontSize: 12,
      lineHeight: 18,
      color: c.soft,
      paddingHorizontal: n.padding,
      paddingBottom: n.padding,
    },
    connectionCard: {
      borderRadius: g.controlRadius,
      paddingVertical: 12,
      paddingHorizontal: 14,
    },
    machineRow: {
      borderRadius: g.cardRadius,
      paddingVertical: wide ? 14 : 12,
      paddingHorizontal: 16,
    },
    machineTile: {
      width: wide ? 40 : 32,
      height: wide ? 40 : 32,
      borderRadius: g.controlRadius,
    },
    hubTile: { backgroundColor: c.accent },
    hubTag: { backgroundColor: c.accent, borderColor: c.accent },
    machineEnd: { alignItems: "flex-end", gap: 6 },
    machineIdentity: { flexDirection: "row", alignItems: "center", gap: 6 },
    machineName: { flexShrink: 1 },
    machineTag: {
      minHeight: g.tagHeight,
      justifyContent: "center",
      alignSelf: "center",
      borderWidth: 1,
      borderColor: c.divider,
      borderRadius: g.tagRadius,
      paddingHorizontal: g.tagX,
      paddingVertical: g.tagY,
    },
    machineTagText: {
      textTransform: "uppercase",
      fontFamily: "FragmentMono_400Regular",
      fontSize: g.tagFont,
      lineHeight: g.tagLine,
      includeFontPadding: false,
      color: c.ink,
    },
    hubTagText: { color: c.onAccent },
    selfTagText: { color: c.okFg },
    selfTag: { backgroundColor: c.tint, borderColor: "transparent" },
    statDivider: { borderLeftWidth: 1, borderLeftColor: c.divider },
    statValue: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: 20,
      lineHeight: 26,
      color: c.ink,
    },
    statsGrid: { flexDirection: "row", flexWrap: "wrap" },
    statCell: { width: wide ? "25%" : "50%", padding: 12, gap: 6 },
    detailGrid: { flexDirection: wide ? "row" : "column", gap: 16 },
    detailMain: { flex: wide ? 1 : undefined, minWidth: 0, gap: 12 },
    stickySideScroll: { flexGrow: 0 },
    stickySideContent: { gap: 12 },
    detailSide: {
      width: wide ? g.detailSideWidth : undefined,
      flexShrink: 0,
      minWidth: 0,
      gap: 12,
    },
    folderToolbar: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
    },
    folderTools: { gap: 12 },
    historyTools: { flexDirection: "row", alignItems: "center", gap: 8 },
    historyFolderFilter: { width: wide ? 140 : undefined },
    historyGroups: { gap: 24 },
    historyFolder: { width: 110 },
    historyRevision: { width: 64 },
    historyDate: { width: 90 },
    fileMenuOverlay: {
      ...StyleSheet.absoluteFill,
      zIndex: 20,
      elevation: 8,
    },
    fileMenuDismiss: StyleSheet.absoluteFill,
    fileActionMenu: {
      position: "absolute",
      backgroundColor: c.surface,
      borderColor: c.divider,
      borderWidth: 1,
      borderRadius: g.controlRadius,
      shadowColor: "#000",
      shadowOpacity: 0.14,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 8,
    },
    rowAction: { flexDirection: "row", alignItems: "center", gap: 12 },
    compactActions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    rowTitle: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchRowFont,
      lineHeight: g.touchRowLine,
      color: c.ink,
    },
    modalRoot: { flex: 1 },
    modalBackdrop: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(18,26,22,0.32)",
    },
    modalOverlay: {
      flex: 1,
      justifyContent: wide ? "center" : "flex-end",
      alignItems: "center",
      padding: wide ? 24 : 0,
    },
    modalOverlayCentered: { justifyContent: "center", padding: 24 },
    confirmPanel: { maxWidth: 360 },
    confirmHeader: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
    confirmActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 12,
    },
    enter: { gap: g.sectionGap, flexGrow: 1 },
    enterSetup: { gap: 24 },
    sheetScroll: { flexShrink: 1 },
    modalPanel: {
      flexShrink: 1,
      width: "100%",
      maxWidth: wide ? 600 : undefined,
      maxHeight: "95%",
      backgroundColor: c.paper,
      borderRadius: 14,
      overflow: "hidden",
    },
    dangerCard: { borderColor: c.danger },
    destructivePrimary: { backgroundColor: c.danger, borderColor: c.danger },
    dangerButton: { borderColor: c.danger },
    quietButton: {
      flexShrink: 0,
      borderWidth: 0,
      backgroundColor: "transparent",
      paddingHorizontal: 0,
      alignSelf: "flex-start",
    },
    switchTarget: {
      minWidth: 44,
      minHeight: g.touchHeight,
      alignItems: "center",
      justifyContent: "center",
    },
    switchTrack: {
      width: 40,
      height: 24,
      borderRadius: g.cardRadius,
      padding: 3,
      backgroundColor: c.line,
    },
    switchOn: { backgroundColor: c.accent },
    switchThumb: {
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: "#ffffff",
    },
    switchThumbOn: { alignSelf: "flex-end" },
    centerText: { textAlign: "center" },
    scroll: { flex: 1 },
    viewHeader: {
      padding: wide ? g.workspaceInset : 16,
      paddingBottom: g.headerBottomGap,
      gap: 16,
      backgroundColor: c.paper,
      width: "100%",
      maxWidth: 1400,
      alignSelf: "center",
    },
    offlineStatus: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: wide ? g.workspaceInset : 16,
      paddingBottom: 8,
      width: "100%",
      maxWidth: 1400,
      alignSelf: "center",
    },
    detailViewHeader: {
      paddingTop: g.detailHeaderTop,
      gap: g.detailNavigationGap,
    },
    viewBody: { paddingTop: 0 },
    content: {
      padding: wide ? g.workspaceInset : 16,
      gap: g.sectionGap,
      width: "100%",
      maxWidth: 1400,
      alignSelf: "center",
      flexGrow: 1,
    },
    screenHeader: { minHeight: controlHeight },
    screenTitle: { flexDirection: "row", alignItems: "center", gap: 12 },
    title: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: wide ? g.desktopTitleFont : g.touchTitleFont,
      lineHeight: wide ? g.desktopTitleLine : g.touchTitleLine,
      color: c.ink,
      letterSpacing: -0.5,
    },
    detailTitle: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.detailTitleFont,
      lineHeight: g.detailTitleLine,
      color: c.ink,
      flexShrink: 1,
    },
    heading: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchRowFont,
      lineHeight: g.touchRowLine,
      color: c.ink,
    },
    text: {
      fontFamily: "InstrumentSans_400Regular",
      fontSize: g.touchBodyFont,
      lineHeight: g.touchBodyLine,
      color: c.soft,
    },
    caption: {
      fontFamily: "InstrumentSans_400Regular",
      fontSize: g.touchCaptionFont,
      color: c.soft,
      lineHeight: g.touchCaptionLine,
    },
    eyebrow: {
      fontFamily: "FragmentMono_400Regular",
      fontSize: 12,
      lineHeight: 18,
      color: c.mute,
      letterSpacing: 1,
    },
    mono: {
      fontFamily: "FragmentMono_400Regular",
      fontSize: 12,
      lineHeight: 18,
      color: c.soft,
    },
    row: { flexDirection: "row", alignItems: "center", gap: 12 },
    flex: { flex: 1, minWidth: 0 },
    stack: { gap: 4 },
    section: { gap: g.sectionLabelGap },
    group: {
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.divider,
      borderRadius: g.controlRadius,
      overflow: "hidden",
    },
    explorerEmpty: {
      alignItems: "center",
      paddingVertical: 48,
      paddingHorizontal: 20,
      gap: 8,
    },
    settingRow: {
      paddingHorizontal: wide ? 14 : 16,
      paddingVertical: wide ? 10 : 16,
      gap: 8,
    },
    breadcrumb: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 14,
      minHeight: 44,
    },
    breadcrumbButton: { minHeight: 44, justifyContent: "center" },
    separator: { borderTopWidth: 1, borderColor: c.divider },
    settingWithActions: {
      flexDirection: wide ? "row" : "column",
      alignItems: wide ? "center" : "stretch",
      gap: 16,
    },
    settingDescription: { flex: wide ? 1 : undefined, minWidth: 0, gap: 12 },
    settingActions: { flexShrink: 0, maxWidth: wide ? "60%" : "100%" },
    card: {
      backgroundColor: c.surface,
      borderColor: c.divider,
      borderWidth: 1,
      borderRadius: g.cardRadius,
      padding: 16,
      gap: 12,
    },
    available: {
      borderStyle: "dashed",
      borderColor: c.line,
      backgroundColor: c.paper,
    },
    tile: {
      width: 32,
      height: 32,
      borderRadius: g.controlRadius,
      backgroundColor: c.tint,
      alignItems: "center",
      justifyContent: "center",
    },
    button: {
      backgroundColor: c.surface,
      minHeight: g.touchControlHeight,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: g.controlRadius,
      borderWidth: 1,
      borderColor: c.line,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 8,
    },
    primary: { backgroundColor: c.accent, borderColor: c.accent },
    buttonLabel: {
      flexShrink: 0,
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchControlFont,
      lineHeight: g.touchControlLine,
      color: c.ink,
    },
    primaryLabel: { color: c.onAccent },
    disabled: { opacity: 0.5 },
    input: {
      height: controlHeight,
      minHeight: controlHeight,
      includeFontPadding: false,
      textAlignVertical: "center",
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: g.controlRadius,
      paddingHorizontal: wide ? 12 : 16,
      paddingVertical: 0,
      backgroundColor: c.surface,
      color: c.ink,
      fontFamily: "InstrumentSans_400Regular",
      fontSize: g.touchInputFont,
      lineHeight: g.touchInputLine,
    },
    code: {
      fontFamily: "FragmentMono_400Regular",
      fontSize: 25,
      letterSpacing: 8,
      textAlign: "center",
    },
    tabs: {
      flexDirection: "row",
      borderTopWidth: 1,
      borderColor: c.divider,
      backgroundColor: c.paper,
      paddingTop: 8,
      paddingHorizontal: 8,
      paddingBottom: 4,
      gap: 4,
    },
    tab: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 5,
      minHeight: 60,
      paddingVertical: 6,
      borderRadius: g.controlRadius,
    },
    tabSelectedLabel: { fontFamily: "InstrumentSans_600SemiBold" },
    active: { color: c.accent },
    error: { backgroundColor: c.dangerBg, borderColor: c.danger },
    errorText: { color: c.danger },
    center: { alignItems: "center", gap: 16, paddingVertical: 26 },
    logo: { width: 76, height: 76 },
    folderList: { gap: g.listItemGap },
    badgeIcon: {
      minHeight: g.pillLine + g.pillY * 2,
      justifyContent: "center",
    },
    badge: {
      flexDirection: "row",
      alignItems: "center",
      gap: g.pillGap,
      backgroundColor: c.tint,
      borderRadius: g.pillRadius,
      paddingLeft: g.pillLeft,
      paddingRight: g.pillRight,
      paddingVertical: g.pillY,
      alignSelf: "flex-start",
    },
    badgeText: {
      color: c.okFg,
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.pillFont,
      lineHeight: g.pillLine,
      includeFontPadding: false,
    },
  };
  for (const rule of Object.values(rules)) {
    if (!rule || typeof rule !== "object") continue;
    if (typeof rule.fontSize === "number") rule.fontSize *= textScale;
    if (typeof rule.lineHeight === "number") rule.lineHeight *= textScale;
  }
  return StyleSheet.create(rules);
}
