import { noticeMetrics as n } from "../../desktop/src/notice-contract.js";
import { StyleSheet } from "react-native";
import { geometry as g } from "./design-tokens.js";
import { palettes } from "./palette.js";
export { palettes };
export function styles(
  c,
  wide = false,
  compact = false,
  fontScale = 1,
  textScale = 1,
) {
  const controlHeight = Math.max(
    g.touchControlHeight,
    Math.ceil(26 * fontScale * textScale + 18),
  );
  const rules = {
    scaffoldRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: c.divider,
      borderRadius: g.cardRadius,
      backgroundColor: c.surface,
    },
    scaffoldDashed: { borderStyle: "dashed", backgroundColor: c.paper },
    scaffoldMark: {
      width: 40,
      height: 40,
      borderRadius: g.controlRadius,
      backgroundColor: c.hover,
    },
    scaffoldDot: { width: 10, height: 10, borderRadius: 5 },
    scaffoldCopy: { flex: 1, gap: 8 },
    scaffoldLine: {
      height: 12,
      borderRadius: g.segmentRadius,
      backgroundColor: c.hover,
      opacity: 0.65,
    },
    scaffoldTitle: { height: 16, width: "60%" },
    scaffoldLong: { width: "85%" },
    scaffoldShort: { width: 40 },

    dateRailOverlay: {
      position: "absolute",
      right: 0,
      width: 184,
      zIndex: 20,
    },
    scrubThumb: {
      position: "absolute",
      top: 0,
      right: 4,
      width: 36,
      height: 48,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 18,
      backgroundColor: c.accent,
      shadowColor: "#000",
      shadowOpacity: 0.22,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 3 },
      elevation: 6,
    },
    flipped: { transform: [{ rotate: "180deg" }], marginBottom: -4 },
    scrubTrack: {
      position: "absolute",
      top: 24,
      bottom: 24,
      right: 21,
      width: 2,
      borderRadius: 1,
      backgroundColor: c.line,
    },
    scrubYear: {
      position: "absolute",
      right: 52,
      transform: [{ translateY: -11 }],
      overflow: "hidden",
      paddingHorizontal: 8,
      borderRadius: g.pillRadius,
      borderWidth: 1,
      borderColor: c.divider,
      backgroundColor: c.surface,
      color: c.ink,
      fontSize: 12,
      lineHeight: 20,
      fontFamily: "InstrumentSans_600SemiBold",
    },
    scrubBubble: {
      position: "absolute",
      top: 0,
      right: 52,
      minWidth: 96,
      height: 32,
      paddingHorizontal: 14,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: g.pillRadius,
      backgroundColor: c.accent,
      shadowColor: "#000",
      shadowOpacity: 0.22,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 3 },
      elevation: 6,
    },
    scrubBubbleText: {
      color: c.onAccent,
      fontSize: 14,
      lineHeight: 18,
      fontFamily: "InstrumentSans_600SemiBold",
    },
    yearMosaic: { flexDirection: "row", flexWrap: "wrap", gap: 2 },
    yearTile: {
      overflow: "hidden",
      borderRadius: 2,
      backgroundColor: c.placeholder,
    },
    timeline: { gap: 20 },
    timelineStatus: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      minHeight: 24,
    },
    pendingUploads: {
      padding: 12,
      gap: 12,
      borderWidth: 1,
      borderColor: c.divider,
      borderRadius: g.cardRadius,
      backgroundColor: c.surface,
    },
    pendingHeader: { flexWrap: "wrap", rowGap: 4 },
    pendingTitle: { flexGrow: 1 },
    pendingUploadStrip: { gap: 8 },
    timelineGroup: { gap: 8 },
    galleryCanvas: { position: "relative" },
    galleryCell: { position: "absolute" },
    galleryHeader: { position: "absolute", left: 0, right: 0 },
    timelineMonth: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchRowFont,
      lineHeight: g.touchRowLine,
      color: c.ink,
    },
    photoTile: {
      borderRadius: 4,
      overflow: "hidden",
      backgroundColor: c.placeholder,
    },
    photoBadge: {
      position: "absolute",
      bottom: 4,
      right: 4,
      padding: 3,
      borderRadius: g.pillRadius,
      backgroundColor: "rgba(0,0,0,0.55)",
    },
    viewerRoot: { flex: 1, backgroundColor: "#000" },
    viewerPage: {
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      gap: 12,
      padding: 24,
    },
    viewerVideoPoster: {
      position: "absolute",
      width: "100%",
      height: "100%",
      opacity: 0.6,
    },
    viewerPreview: {
      position: "absolute",
      width: "100%",
      height: "100%",
    },
    viewerVideoSurface: {
      flex: 1,
      width: "100%",
      marginTop: 90,
      marginBottom: 110,
    },
    viewerVideo: { flex: 1, width: "100%" },
    viewerVideoLoading: {
      position: "absolute",
      top: 0,
      bottom: 0,
      left: 0,
      right: 0,
      alignItems: "center",
      justifyContent: "center",
    },
    viewerPlay: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: "rgba(255,255,255,0.18)",
      alignItems: "center",
      justifyContent: "center",
    },
    viewerChrome: {
      position: "absolute",
      left: 0,
      right: 0,
      paddingHorizontal: 12,
      backgroundColor: "rgba(0,0,0,0.6)",
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    viewerTop: { top: 0, paddingBottom: 8 },
    viewerTitle: {
      color: "#fff",
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchBodyFont,
      lineHeight: g.touchBodyLine,
    },
    viewerCaption: {
      color: "rgba(255,255,255,0.72)",
      fontFamily: "InstrumentSans_400Regular",
      fontSize: g.touchCaptionFont,
      lineHeight: g.touchCaptionLine,
      textAlign: "center",
    },
    infoPanel: {
      position: "absolute",
      backgroundColor: c.paper,
      overflow: "hidden",
    },
    infoSheet: {
      left: 0,
      right: 0,
      bottom: 0,
      maxHeight: "72%",
      borderTopLeftRadius: 14,
      borderTopRightRadius: 14,
    },
    infoSide: {
      top: 0,
      bottom: 0,
      right: 0,
      width: 360,
      borderLeftWidth: 1,
      borderColor: c.line,
    },
    infoBody: { padding: 16, gap: 24 },
    infoIdentity: { gap: 8, paddingHorizontal: 4 },
    infoFilename: {
      color: c.ink,
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchBodyFont,
      lineHeight: g.touchBodyLine,
    },
    infoCard: {
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: g.controlRadius,
      padding: 16,
      gap: 20,
    },
    infoValues: { gap: 4 },
    infoLabel: {
      color: c.mute,
      fontFamily: "InstrumentSans_400Regular",
      fontSize: g.touchCaptionFont,
      lineHeight: g.touchCaptionLine,
    },
    infoMetricValue: {
      color: c.ink,
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchBodyFont,
      lineHeight: g.touchBodyLine,
    },
    infoLink: {
      color: c.accent,
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchBodyFont,
      lineHeight: g.touchBodyLine,
    },
    infoRow: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
    infoMetrics: {
      flexDirection: "row",
      flexWrap: "wrap",
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: g.controlRadius,
      backgroundColor: c.surface,
    },
    infoMetric: { width: "50%", padding: 12, gap: 4 },
    infoFooter: {
      flexDirection: "row",
      padding: 16,
      borderTopWidth: 1,
      borderColor: c.divider,
    },
    viewerIconButton: {
      width: g.touchHeight,
      height: g.touchHeight,
      alignItems: "center",
      justifyContent: "center",
    },
    galleryGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    galleryTile: {
      width: "23%",
      aspectRatio: 1,
      borderRadius: g.controlRadius,
      overflow: "hidden",
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.line,
    },
    galleryImage: { width: "100%", height: "100%" },
    musicPage: { gap: 16 },
    musicBack: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    musicCover: {
      borderRadius: g.controlRadius,
      overflow: "hidden",
      backgroundColor: c.placeholder,
      alignItems: "center",
      justifyContent: "center",
    },
    musicCoverFill: { width: "100%", aspectRatio: 1 },
    musicGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
    musicAlbum: { width: wide ? "18%" : "30.5%", gap: 4 },
    musicPressed: { opacity: 0.7 },
    musicTrack: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      minHeight: g.touchControlHeight + 2 * g.listRowPaddingY,
      paddingVertical: g.listRowPaddingY,
      paddingHorizontal: g.listRowPaddingX,
      backgroundColor: c.surface,
    },
    musicNumber: { width: 28, alignItems: "center" },
    musicPending: { color: c.mute },
    musicRowAction: {
      width: g.touchHeight,
      height: g.touchHeight,
      alignItems: "center",
      justifyContent: "center",
    },
    musicHeader: { flexDirection: "row", alignItems: "center", gap: 16 },
    musicHeaderWide: { gap: 24 },
    musicActions: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginTop: 8,
    },
    miniPlayer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginHorizontal: wide ? g.workspaceInset : 12,
      marginBottom: 8,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: g.cardRadius,
      borderWidth: 1,
      borderColor: c.divider,
      backgroundColor: c.surface,
    },
    miniControl: {
      width: g.touchHeight,
      height: g.touchHeight,
      alignItems: "center",
      justifyContent: "center",
    },
    nowPlaying: { alignItems: "center", gap: 20, paddingBottom: 8 },
    nowPlayingText: { alignSelf: "stretch", alignItems: "center" },
    playerProgressArea: { alignSelf: "stretch", gap: 6 },
    playerTrackArea: { minHeight: g.touchHeight, justifyContent: "center" },
    playerTrack: {
      height: 6,
      borderRadius: 3,
      backgroundColor: c.line,
      overflow: "hidden",
    },
    playerFill: { height: "100%", backgroundColor: c.accent },
    playerTimes: { flexDirection: "row", justifyContent: "space-between" },
    playerControls: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      alignSelf: "stretch",
    },
    playerControl: {
      width: g.touchControlHeight,
      height: g.touchControlHeight,
      alignItems: "center",
      justifyContent: "center",
    },
    playButton: {
      width: g.touchControlHeight + 16,
      height: g.touchControlHeight + 16,
      borderRadius: 999,
      backgroundColor: c.accent,
      alignItems: "center",
      justifyContent: "center",
    },
    mediaPlaceholder: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      padding: 4,
      backgroundColor: c.placeholder,
    },
    root: { flex: 1, backgroundColor: c.paper },
    shell: { flexDirection: "row" },
    setup: { maxWidth: 480, paddingHorizontal: 24, paddingTop: 32, gap: 24 },
    displayTitle: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: 36,
      lineHeight: 38,
      letterSpacing: -1.4,
      color: c.ink,
    },
    emphasis: { fontStyle: "italic", color: c.accent },
    featureRow: { flexDirection: "row", alignItems: "flex-start", gap: 16 },
    tileLarge: { width: g.touchHeight, height: g.touchHeight },
    selectedCard: { borderColor: c.accent },
    selectionCheck: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: c.accent,
      alignItems: "center",
      justifyContent: "center",
    },
    inputShell: {
      height: controlHeight,
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      gap: 12,
      borderWidth: 1,
      borderColor: c.control,
      borderRadius: g.controlRadius,
      backgroundColor: c.surface,
    },
    inputEmbedded: {
      height: controlHeight - 2,
      minHeight: 0,
      flex: 1,
      minWidth: 0,
      borderWidth: 0,
      paddingHorizontal: 0,
    },
    codeControl: { position: "relative" },
    codeCells: { flexDirection: "row", alignItems: "center", gap: 6 },
    codeCell: {
      flex: 1,
      minHeight: 54,
      borderWidth: 1,
      borderColor: c.control,
      borderRadius: g.controlRadius,
      backgroundColor: c.surface,
      alignItems: "center",
      justifyContent: "center",
    },
    codeDigit: {
      fontFamily: "FragmentMono_400Regular",
      fontSize: 24,
      color: c.ink,
    },
    codeSeparator: { fontSize: 24, color: c.line },
    codeCapture: {
      ...StyleSheet.absoluteFill,
      opacity: 0.02,
      color: "transparent",
      fontSize: 24,
    },
    controlFocused: {
      borderColor: c.accent,
      outlineWidth: 3,
      outlineColor: c.tint,
      outlineStyle: "solid",
    },
    stepIndicator: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
    },
    stepDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: c.line },
    stepDotActive: { width: 20, backgroundColor: c.accent },
    centeredRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
    },
    navigation: {
      width: compact ? 64 : 200,
      backgroundColor: c.side,
      borderRightWidth: 1,
      borderColor: c.divider,
      padding: compact ? 10 : 12,
      paddingTop: g.workspaceInset,
      gap: 8,
    },
    brand: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      minHeight: controlHeight,
    },
    identity: {
      flexDirection: "row",
      alignItems: "center",
      minHeight: 36,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.divider,
      borderRadius: g.controlRadius,
      paddingHorizontal: 8,
      gap: 8,
    },
    tileAvailable: { backgroundColor: c.hover },
    segments: {
      alignSelf: wide ? "flex-start" : "stretch",
      flexDirection: "row",
      backgroundColor: c.segmentTrack,
      borderRadius: g.controlRadius,
      padding: 3,
      gap: 2,
    },
    segment: {
      flex: wide ? 0 : 1,
      paddingHorizontal: wide ? 12 : 0,
      minHeight: 38,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: g.segmentRadius,
    },
    segmentText: { color: c.soft },
    segmentTextSelected: { color: c.ink },
    segmentSelected: {
      backgroundColor: c.segmentSelected,
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 2,
      elevation: 1,
    },
    navItem: {
      minHeight: g.touchHeight,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 12,
      borderRadius: g.controlRadius,
    },
    compactNav: { paddingHorizontal: 0, justifyContent: "center" },
    compactBrand: { justifyContent: "center" },
    navLabel: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchCaptionFont,
      lineHeight: g.touchControlLine,
      color: c.ink,
    },
    navSelected: { backgroundColor: c.tint },
    navFooter: { marginTop: "auto", padding: 12, gap: 6 },
    folderRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      minHeight: g.touchControlHeight + 2 * g.listRowPaddingY + 2,
      paddingVertical: g.listRowPaddingY,
      paddingHorizontal: g.listRowPaddingX,
      borderRadius: g.controlRadius,
    },
    groupedFolderRow: { backgroundColor: c.surface, borderRadius: 0 },
    actionRow: {
      flexDirection: "row",
      alignItems: "center",
      minHeight: g.touchControlHeight,
      paddingVertical: 8,
      paddingHorizontal: wide ? g.workspaceInset : 16,
      gap: 16,
    },
    deletedFile: { textDecorationLine: "line-through" },
    conflictChoice: { borderWidth: 2, borderColor: c.divider, gap: 8 },
    conflictChoiceSelected: { borderColor: c.accent },
    actionGroup: { overflow: "hidden" },
    destructiveActionGroup: {
      marginTop: 8,
      paddingTop: 8,
      borderTopWidth: 1,
      borderColor: c.divider,
    },
    sheetHandle: {
      width: 36,
      height: 5,
      borderRadius: 3,
      backgroundColor: c.line,
      alignSelf: "center",
      marginTop: 8,
      marginBottom: 4,
    },
    approvalTitle: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchTitleFont,
      lineHeight: g.touchTitleLine,
      color: c.ink,
    },
    centerText: { textAlign: "center" },
    requestReference: {
      borderWidth: 1,
      borderStyle: "dashed",
      borderColor: c.line,
      borderRadius: g.cardRadius,
      padding: g.sectionGap,
      gap: g.listItemGap,
      marginVertical: 8,
    },
    requestNumber: {
      fontFamily: "FragmentMono_400Regular",
      fontSize: g.approvalReferenceFont,
      lineHeight: g.touchControlHeight,
      letterSpacing: g.referenceTracking,
      textAlign: "center",
      color: c.ink,
    },
    requestSeparator: { color: c.line },
    approvalRow: {
      flexDirection: "row",
      alignItems: "center",
      padding: g.listRowPaddingX,
      gap: g.listRowPaddingY,
    },
    approvalRowBorder: { borderTopWidth: 1, borderColor: c.divider },
    approvalValue: { flex: 1, textAlign: "right", fontSize: g.touchBodyFont },
    sheetHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      minHeight: g.touchControlHeight + 16,
      paddingHorizontal: wide ? g.workspaceInset : 16,
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderColor: c.divider,
    },
    sheetHeaderDialog: { paddingTop: 12 },
    sheetMenu: { paddingVertical: 8 },
    iconButton: {
      width: g.touchControlHeight,
      height: g.touchControlHeight,
      paddingHorizontal: 0,
      paddingVertical: 0,
    },
    smallButton: {
      minHeight: g.buttonSmallHeight,
      paddingVertical: 4,
      paddingHorizontal: 10,
    },
    smallIconButton: {
      width: g.buttonSmallHeight,
      height: g.buttonSmallHeight,
      paddingHorizontal: 0,
      paddingVertical: 0,
    },
    detailTile: {
      width: g.detailTile,
      height: g.detailTile,
      borderRadius: g.cardRadius,
    },
    badgeWarning: { backgroundColor: c.warningBg },
    badgeWarningText: { color: c.warning },
    badgeError: { backgroundColor: c.dangerBg },
    badgeNeutral: { backgroundColor: c.hover },
    badgeBusy: { backgroundColor: "transparent" },
    badgeNeutralText: { color: c.soft },
    noticeDock: {
      position: "absolute",
      left: n.inset,
      right: n.inset,
      alignItems: "center",
    },
    noticeStackScroll: { width: "100%", maxWidth: n.width, flexGrow: 0 },
    noticeStack: { gap: n.gap },
    noticeCard: {
      backgroundColor: c.noticeSurface,
      borderWidth: 1,
      borderColor: c.divider,
      borderRadius: n.radius,
      overflow: "hidden",
      shadowColor: "#000",
      shadowOpacity: 0.14,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    noticeInfo: {
      backgroundColor: c.noticeInfoBg,
      borderColor: c.noticeInfoBg,
    },
    noticeMain: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: n.gap,
      padding: n.padding,
    },
    noticeTitle: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: n.title,
      lineHeight: n.line,
      color: c.ink,
    },
    noticeText: {
      fontFamily: "InstrumentSans_400Regular",
      fontSize: n.body,
      lineHeight: n.line,
      color: c.soft,
      marginTop: 3,
    },
    noticeInfoText: { color: c.noticeInfoFg },
    noticeInfoLink: { color: c.noticeInfoLink },
    noticeMuted: { color: c.mute },
    noticeActions: {
      flexDirection: "row",
      gap: n.gap,
      flexWrap: "wrap",
      marginTop: 4,
    },
    noticeLink: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: n.body,
      lineHeight: n.line,
      color: c.noticeLink,
    },
    noticeLinkTarget: { minHeight: g.touchHeight, justifyContent: "center" },
    noticeClose: {
      width: 16,
      height: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    noticeDetails: {
      backgroundColor: c.paper,
      borderTopWidth: 1,
      borderColor: c.divider,
    },
    noticeDetailsHead: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: n.padding,
    },
    noticeDetailsToggle: {
      flex: 1,
      flexDirection: "row",
      gap: 8,
      minHeight: g.touchHeight,
      alignItems: "center",
    },
    noticeDetailsLabel: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: 13,
      color: c.soft,
    },
    noticeTraceScroll: { maxHeight: 180 },
    noticeTrace: {
      fontFamily: "FragmentMono_400Regular",
      fontSize: 12,
      lineHeight: 18,
      color: c.soft,
      paddingHorizontal: n.padding,
      paddingBottom: n.padding,
    },
    connectionCard: {
      borderRadius: g.controlRadius,
      paddingVertical: 12,
      paddingHorizontal: 14,
    },
    machineRow: {
      borderRadius: g.cardRadius,
      paddingVertical: wide ? 14 : 12,
      paddingHorizontal: 16,
    },
    machineTile: {
      width: wide ? 40 : 32,
      height: wide ? 40 : 32,
      borderRadius: g.controlRadius,
    },
    hubTile: { backgroundColor: c.accent },
    hubTag: { backgroundColor: c.accent, borderColor: c.accent },
    machineEnd: { alignItems: "flex-end", gap: 6 },
    machineAway: { borderStyle: "dashed", backgroundColor: c.paper },
    machineChosen: { borderColor: c.accent },
    reportLine: { flexDirection: "row", alignItems: "center", gap: 4 },
    reportText: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchCaptionFont,
      lineHeight: g.touchCaptionLine,
    },
    deviceTree: { marginLeft: 16, gap: g.listItemGap },
    deviceBranch: { marginLeft: 0, paddingLeft: 24 },
    branchLine: {
      position: "absolute",
      left: 0,
      top: -g.listItemGap,
      bottom: "50%",
      width: 24,
      borderLeftWidth: 2,
      borderBottomWidth: 2,
      borderBottomLeftRadius: g.cardRadius,
      borderColor: c.accent,
    },
    branchLineDashed: { borderStyle: "dashed", borderColor: c.warning },
    searchRow: { flexDirection: "row", alignItems: "center", gap: 12, minHeight: g.touchControlHeight, paddingVertical: 6, paddingHorizontal: 8, borderRadius: g.controlRadius },
    searchCover: { width: 32, height: 32, borderRadius: 4, backgroundColor: c.placeholder },
    searchGroup: { gap: 4 },
    searchLabel: { flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 8, paddingTop: 12 },
    searchBody: { paddingHorizontal: 8, paddingBottom: 24, gap: 4 },
    searchEmpty: { alignItems: "center", gap: 8, padding: 32 },
    searchThumbs: { flexDirection: "row", gap: 6, paddingHorizontal: 8 },
    searchThumb: { flex: 1, aspectRatio: 1, borderRadius: g.controlRadius, overflow: "hidden", alignItems: "center", justifyContent: "center", backgroundColor: c.placeholder, borderWidth: 1, borderColor: "transparent" },
    searchThumbImage: { width: "100%", height: "100%" },
    searchForget: { width: g.touchControlHeight, height: g.touchControlHeight, alignItems: "center", justifyContent: "center" },
    searchCancel: { minHeight: g.touchControlHeight, justifyContent: "center", paddingHorizontal: 8 },
    searchField: { flexDirection: "row", alignItems: "center", gap: 8, minHeight: g.touchControlHeight + 8, paddingHorizontal: 12, borderBottomWidth: 1, borderBottomColor: c.divider },
    searchInput: { flex: 1, minHeight: g.touchControlHeight, fontFamily: "InstrumentSans_400Regular", fontSize: 16, color: c.ink },
    searchChips: { flexDirection: "row", gap: 8, paddingHorizontal: 12, paddingVertical: 8 },
    searchChip: { minHeight: g.touchControlHeight, justifyContent: "center", paddingHorizontal: 14, borderRadius: 999, borderWidth: 1, borderColor: c.divider, backgroundColor: c.surface },
    searchChipOn: { backgroundColor: c.accent, borderColor: c.accent },
    searchChipText: { color: c.onAccent },
    searchScreen: { flex: 1, backgroundColor: c.paper },
    searchFull: { flex: 1 },
    searchBackdrop: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(18, 26, 22, 0.32)" },
    searchDialog: { width: 680, maxWidth: "94%", maxHeight: "86%", borderRadius: g.cardRadius, backgroundColor: c.noticeSurface, overflow: "hidden" },
    searchSplit: { flexDirection: "row", flex: 1, minHeight: 320 },
    searchPane: { width: 260, gap: 8, padding: 16, borderLeftWidth: 1, borderLeftColor: c.divider },
    searchFieldRow: { flexDirection: "row", alignItems: "center", gap: 8, minHeight: g.touchControlHeight, paddingHorizontal: 14, borderWidth: 1, borderColor: c.control, borderRadius: g.controlRadius, backgroundColor: c.surface },
    viewerTransparent: { backgroundColor: "transparent" },
    viewerBackdrop: { backgroundColor: "#000" },
    viewerStrip: { position: "absolute", left: 0, right: 0, bottom: 0, gap: 8, paddingTop: 8, backgroundColor: "rgba(0,0,0,0.55)" },
    viewerCount: { alignSelf: "center", fontFamily: "FragmentMono_400Regular", fontSize: 12, color: "#fff" },
    viewerThumb: { width: 48, height: 48, marginRight: 4, borderRadius: 6, overflow: "hidden", backgroundColor: "rgba(255,255,255,0.12)", borderWidth: 2, borderColor: "transparent" },
    viewerThumbOn: { borderColor: "#fff" },
    viewerThumbImage: { width: "100%", height: "100%" },
    nowRoot: { flex: 1, backgroundColor: c.tint },
    nowHeader: { flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 8, minHeight: g.touchControlHeight + 8 },
    viewerIconButtonDark: { width: g.touchControlHeight, height: g.touchControlHeight, alignItems: "center", justifyContent: "center" },
    nowScroll: { flexGrow: 1, backgroundColor: c.paper, paddingBottom: 24 },
    nowPage: { alignItems: "center", gap: 16, paddingTop: 24, paddingHorizontal: 24 },
    nowLinks: { alignItems: "center", gap: 2 },
    nowLink: { color: c.accent, textDecorationLine: "underline" },
    nowUpNext: { flexDirection: "row", alignItems: "center", gap: 8, alignSelf: "stretch", minHeight: g.touchControlHeight, paddingHorizontal: 12, borderRadius: g.controlRadius, borderWidth: 1, borderColor: c.divider, backgroundColor: c.surface },
    nowSplit: { flex: 1, flexDirection: "row" },
    nowQueue: { width: g.detailSideWidth, backgroundColor: c.paper, borderLeftWidth: 1, borderLeftColor: c.divider },
    nowQueueScrim: { position: "absolute", left: 0, right: 0, top: 0, bottom: 0 },
    nowQueueHead: { flexDirection: "row", alignItems: "center", paddingLeft: 16, paddingRight: 4 },
    nowQueueSheet: { position: "absolute", left: 0, right: 0, bottom: 0, height: "55%", backgroundColor: c.surface, borderTopLeftRadius: g.cardRadius, borderTopRightRadius: g.cardRadius, borderWidth: 1, borderColor: c.divider },
    rowThumb: {
      width: g.touchHeight,
      height: g.touchHeight,
      borderRadius: g.controlRadius,
      overflow: "hidden",
      backgroundColor: c.placeholder,
    },
    rowThumbImage: { width: "100%", height: "100%" },
    previewStage: {
      minHeight: 160,
      maxHeight: 320,
      borderRadius: g.cardRadius,
      overflow: "hidden",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: c.placeholder,
    },
    previewImage: { width: "100%", height: 280 },
    previewText: {
      alignSelf: "stretch",
      padding: 16,
      backgroundColor: c.surface,
      fontFamily: "FragmentMono_400Regular",
      fontSize: 13,
      lineHeight: 20,
      color: c.ink,
    },
    homeLead: {
      width: g.touchControlHeight,
      height: g.touchControlHeight,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: g.cardRadius,
    },
    homeConflict: { borderWidth: 2, borderColor: c.warning },
    arrivals: { gap: 8 },
    arrival: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      minHeight: g.touchControlHeight,
      maxWidth: 240,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderWidth: 1,
      borderColor: c.divider,
      borderRadius: g.controlRadius,
      backgroundColor: c.surface,
    },
    activityStrip: {
      gap: 8,
      padding: 12,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.divider,
      borderRadius: g.cardRadius,
    },
    activityHead: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      minHeight: 24,
    },
    activityChip: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 999,
      backgroundColor: c.ink,
    },
    activityChipText: {
      fontFamily: "FragmentMono_400Regular",
      fontSize: 12,
      color: c.paper,
    },
    activityBars: {
      flexDirection: "row",
      alignItems: "flex-end",
      height: g.touchControlHeight + 16,
      paddingTop: 12,
      borderBottomWidth: 1,
      borderBottomColor: c.divider,
    },
    activityBar: {
      flex: 1,
      alignItems: "center",
      justifyContent: "flex-end",
      height: "100%",
    },
    activityBarHeld: { backgroundColor: c.hover },
    activityFill: {
      width: "60%",
      maxWidth: 12,
      borderTopLeftRadius: 3,
      borderTopRightRadius: 3,
      backgroundColor: c.accent,
      opacity: 0.5,
    },
    activityFillStrong: { opacity: 1 },
    activityDot: { width: 8, height: 8, borderRadius: 4, marginBottom: 2 },
    activityLegend: { flexDirection: "row", gap: 12 },
    activityLegendChanges: { backgroundColor: c.accent },
    activityLegendText: {
      fontFamily: "FragmentMono_400Regular",
      fontSize: 12,
      color: c.mute,
    },
    activityConflict: { backgroundColor: c.warning },
    activityDeleted: { backgroundColor: c.danger },
    activityAxis: { flexDirection: "row", justifyContent: "space-between" },
    activityToday: { color: c.accent },
    awayBanner: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 12,
      paddingHorizontal: 14,
    },
    awayDismiss: {
      width: g.touchControlHeight,
      height: g.touchControlHeight,
      alignItems: "center",
      justifyContent: "center",
    },
    daySummary: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 12 },
    dayDevice: { flexDirection: "row", alignItems: "center", gap: 4 },
    historyPane: { flexDirection: "row", gap: 16, alignItems: "flex-start" },
    historyPaneList: { flex: 1, minWidth: 0, gap: g.sectionGap },
    historyPaneSide: {
      width: g.detailSideWidth,
      gap: 12,
      padding: 16,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.divider,
      borderRadius: g.cardRadius,
    },
    historyRowChosen: { backgroundColor: c.hover },
    deviceMapPlain: { gap: g.sectionGap },
    deviceMapRow: { flexDirection: "row", gap: 16, alignItems: "flex-start" },
    deviceMapMain: { flex: 1, minWidth: 0, gap: g.sectionGap },
    deviceMapSide: { width: g.detailSideWidth, gap: 6 },
    deviceMapNode: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      minHeight: g.touchControlHeight,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: c.divider,
      borderRadius: g.controlRadius,
      backgroundColor: c.paper,
    },
    machineIdentity: { flexDirection: "row", alignItems: "center", gap: 6 },
    machineName: { flexShrink: 1 },
    machineTag: {
      minHeight: g.tagHeight,
      justifyContent: "center",
      alignSelf: "center",
      borderWidth: 1,
      borderColor: c.divider,
      borderRadius: g.tagRadius,
      paddingHorizontal: g.tagX,
      paddingVertical: g.tagY,
    },
    machineTagText: {
      textTransform: "uppercase",
      fontFamily: "FragmentMono_400Regular",
      fontSize: g.tagFont,
      lineHeight: g.tagLine,
      includeFontPadding: false,
      color: c.ink,
    },
    hubTagText: { color: c.onAccent },
    selfTagText: { color: c.okFg },
    selfTag: { backgroundColor: c.tint, borderColor: "transparent" },
    statDivider: { borderLeftWidth: 1, borderLeftColor: c.divider },
    statValue: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchRowFont,
      lineHeight: g.touchRowLine,
      color: c.ink,
    },
    statsGrid: { flexDirection: "row", flexWrap: "wrap" },
    statCell: { width: wide ? "25%" : "50%", padding: 12, gap: 6 },
    statCellThird: { width: wide ? "33.333%" : "50%", padding: 12, gap: 6 },
    statCellWide: { width: "100%" },
    detailGrid: { flexDirection: wide ? "row" : "column", gap: 16 },
    detailMain: { flex: wide ? 1 : undefined, minWidth: 0, gap: 12 },
    stickySideScroll: { flexGrow: 0 },
    stickySideContent: { gap: 12 },
    detailSide: {
      width: wide ? g.detailSideWidth : undefined,
      flexShrink: 0,
      minWidth: 0,
      gap: 12,
    },
    folderToolbar: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
    },
    folderTools: { gap: 12 },
    historyTools: { flexDirection: "row", alignItems: "center", gap: 8 },
    historyFolderFilter: { width: wide ? 140 : undefined },
    historyGroups: { gap: 24 },
    historyFolder: { width: 110 },
    historyRevision: { width: 64 },
    historyDate: { width: 90, fontVariant: ["tabular-nums"] },
    tabularTime: { fontVariant: ["tabular-nums"] },
    fileMenuOverlay: {
      ...StyleSheet.absoluteFill,
      zIndex: 20,
      elevation: 8,
    },
    fileMenuDismiss: StyleSheet.absoluteFill,
    fileActionMenu: {
      position: "absolute",
      backgroundColor: c.surface,
      borderColor: c.divider,
      borderWidth: 1,
      borderRadius: g.controlRadius,
      shadowColor: "#000",
      shadowOpacity: 0.14,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 8,
    },
    rowAction: { flexDirection: "row", alignItems: "center", gap: 12 },
    compactActions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    rowTitle: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchRowFont,
      lineHeight: g.touchRowLine,
      color: c.ink,
    },
    modalRoot: { flex: 1 },
    modalBackdrop: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(18,26,22,0.32)",
    },
    modalOverlay: {
      flex: 1,
      justifyContent: wide ? "center" : "flex-end",
      alignItems: "center",
      padding: wide ? 24 : 0,
    },
    modalOverlayCentered: { justifyContent: "center", padding: 24 },
    confirmPanel: { maxWidth: 360 },
    confirmHeader: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
    confirmActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 12,
    },
    enter: { gap: g.sectionGap, flexGrow: 1 },
    enterSetup: { gap: 24 },
    sheetScroll: { flexShrink: 1 },
    modalPanel: {
      flexShrink: 1,
      width: "100%",
      maxWidth: wide ? 600 : undefined,
      maxHeight: "95%",
      backgroundColor: c.raised,
      borderWidth: 1,
      borderColor: c.raisedEdge,
      borderRadius: 14,
      overflow: "hidden",
    },
    pressed: { backgroundColor: c.hover },
    pressedFade: { opacity: 0.85 },
    dangerCard: { borderColor: c.danger },
    destructivePrimary: { backgroundColor: c.danger, borderColor: c.danger },
    dangerButton: { borderColor: c.danger },
    quietButton: {
      flexShrink: 0,
      borderWidth: 0,
      backgroundColor: "transparent",
      paddingHorizontal: 0,
      alignSelf: "flex-start",
    },
    switchTarget: {
      minWidth: 44,
      minHeight: g.touchHeight,
      alignItems: "center",
      justifyContent: "center",
    },
    switchTrack: {
      width: 40,
      height: 24,
      borderRadius: g.cardRadius,
      padding: 3,
      backgroundColor: c.line,
    },
    switchOn: { backgroundColor: c.accent },
    switchThumb: {
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: "#ffffff",
    },
    switchThumbOn: { alignSelf: "flex-end" },
    centerText: { textAlign: "center" },
    scroll: { flex: 1 },
    viewHeader: {
      padding: wide ? g.workspaceInset : 16,
      paddingBottom: g.headerBottomGap,
      gap: 16,
      backgroundColor: c.paper,
      width: "100%",
      maxWidth: 1400,
      alignSelf: "center",
    },
    detailViewHeader: {
      paddingTop: g.detailHeaderTop,
      gap: g.detailNavigationGap,
    },
    viewBody: { paddingTop: 0 },
    content: {
      padding: wide ? g.workspaceInset : 16,
      gap: g.sectionGap,
      width: "100%",
      maxWidth: 1400,
      alignSelf: "center",
      flexGrow: 1,
    },
    screenHeader: { minHeight: controlHeight },
    screenTitle: { flexDirection: "row", alignItems: "center", gap: 12 },
    title: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: wide ? g.desktopTitleFont : g.touchTitleFont,
      lineHeight: wide ? g.desktopTitleLine : g.touchTitleLine,
      color: c.ink,
      letterSpacing: -0.5,
    },
    detailTitle: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.detailTitleFont,
      lineHeight: g.detailTitleLine,
      color: c.ink,
      flexShrink: 1,
    },
    heading: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchRowFont,
      lineHeight: g.touchRowLine,
      color: c.ink,
    },
    text: {
      fontFamily: "InstrumentSans_400Regular",
      fontSize: g.touchBodyFont,
      lineHeight: g.touchBodyLine,
      color: c.soft,
    },
    caption: {
      fontFamily: "InstrumentSans_400Regular",
      fontSize: g.touchCaptionFont,
      color: c.soft,
      lineHeight: g.touchCaptionLine,
    },
    eyebrow: {
      fontFamily: "FragmentMono_400Regular",
      fontSize: 12,
      lineHeight: 18,
      color: c.mute,
      letterSpacing: 1,
    },
    mono: {
      fontFamily: "FragmentMono_400Regular",
      fontSize: 12,
      lineHeight: 18,
      color: c.soft,
    },
    row: { flexDirection: "row", alignItems: "center", gap: 12 },
    flex: { flex: 1, minWidth: 0 },
    stack: { gap: 4 },
    section: { gap: g.sectionLabelGap },
    group: {
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.divider,
      borderRadius: g.controlRadius,
      overflow: "hidden",
    },
    empty: {
      alignItems: "center",
      gap: 10,
      paddingVertical: 40,
      paddingHorizontal: 20,
      borderWidth: 1,
      borderStyle: "dashed",
      borderColor: c.line,
      borderRadius: g.cardRadius,
    },
    settingRow: {
      paddingHorizontal: wide ? 14 : 16,
      paddingVertical: wide ? 10 : 16,
      gap: 8,
    },
    breadcrumb: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 14,
      minHeight: 44,
    },
    breadcrumbButton: { minHeight: 44, justifyContent: "center" },
    separator: { borderTopWidth: 1, borderColor: c.divider },
    settingWithActions: {
      flexDirection: wide ? "row" : "column",
      alignItems: wide ? "center" : "stretch",
      gap: 16,
    },
    settingDescription: { flex: wide ? 1 : undefined, minWidth: 0, gap: 12 },
    settingActions: { flexShrink: 0, maxWidth: wide ? "60%" : "100%" },
    card: {
      backgroundColor: c.surface,
      borderColor: c.divider,
      borderWidth: 1,
      borderRadius: g.cardRadius,
      padding: 16,
      gap: 12,
    },
    available: {
      borderStyle: "dashed",
      borderColor: c.line,
      backgroundColor: c.paper,
    },
    tile: {
      width: 32,
      height: 32,
      borderRadius: g.controlRadius,
      backgroundColor: c.tint,
      alignItems: "center",
      justifyContent: "center",
    },
    button: {
      backgroundColor: c.surface,
      minHeight: g.touchControlHeight,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: g.controlRadius,
      borderWidth: 1,
      borderColor: c.control,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 8,
    },
    primary: { backgroundColor: c.accent, borderColor: c.accent },
    buttonLabel: {
      flexShrink: 0,
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchControlFont,
      lineHeight: g.touchControlLine,
      color: c.ink,
    },
    primaryLabel: { color: c.onAccent },
    disabled: { opacity: 0.5 },
    input: {
      height: controlHeight,
      minHeight: controlHeight,
      includeFontPadding: false,
      textAlignVertical: "center",
      borderWidth: 1,
      borderColor: c.control,
      borderRadius: g.controlRadius,
      paddingHorizontal: wide ? 12 : 16,
      paddingVertical: 0,
      backgroundColor: c.surface,
      color: c.ink,
      fontFamily: "InstrumentSans_400Regular",
      fontSize: g.touchInputFont,
      lineHeight: g.touchInputLine,
    },
    tabs: {
      flexDirection: "row",
      borderTopWidth: 1,
      borderColor: c.divider,
      backgroundColor: c.paper,
      paddingTop: 8,
      paddingHorizontal: 8,
      paddingBottom: 4,
      gap: 4,
    },
    tab: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 5,
      minHeight: 60,
      paddingVertical: 6,
      borderRadius: g.controlRadius,
    },
    tabSelectedLabel: { fontFamily: "InstrumentSans_600SemiBold" },
    active: { color: c.accent },
    error: { backgroundColor: c.dangerBg, borderColor: c.danger },
    errorText: { color: c.danger },
    logo: { width: 76, height: 76 },
    folderList: { gap: g.listItemGap },
    badgeIcon: {
      minHeight: g.pillLine + g.pillY * 2,
      justifyContent: "center",
    },
    badge: {
      flexDirection: "row",
      alignItems: "center",
      gap: g.pillGap,
      backgroundColor: c.tint,
      borderRadius: g.pillRadius,
      paddingLeft: g.pillLeft,
      paddingRight: g.pillRight,
      paddingVertical: g.pillY,
      alignSelf: "flex-start",
    },
    badgeText: {
      color: c.okFg,
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.pillFont,
      lineHeight: g.pillLine,
      includeFontPadding: false,
    },
  };
  for (const rule of Object.values(rules)) {
    if (!rule || typeof rule !== "object") continue;
    if (typeof rule.fontSize === "number") rule.fontSize *= textScale;
    if (typeof rule.lineHeight === "number") rule.lineHeight *= textScale;
  }
  return StyleSheet.create(rules);
}
