import { noticeMetrics as n } from "../../desktop/src/notice-contract.js";
import { StyleSheet } from "react-native";
import { geometry as g } from "./design-tokens.js";
import { palettes } from "./palette.js";
export { palettes };
export function styles(c, wide = false, compact = false, fontScale = 1) {
  const controlHeight = Math.max(
    g.touchControlHeight,
    Math.ceil(26 * fontScale + 18),
  );
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: c.paper },
    shell: { flexDirection: "row" },
    setup: { maxWidth: 480, paddingHorizontal: 24, paddingTop: 32, gap: 24 },
    displayTitle: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: 36,
      lineHeight: 38,
      letterSpacing: -1.4,
      color: c.ink,
    },
    emphasis: { fontStyle: "italic", color: c.accent },
    featureRow: { flexDirection: "row", alignItems: "flex-start", gap: 16 },
    tileLarge: { width: g.touchHeight, height: g.touchHeight },
    selectedCard: { borderColor: c.accent },
    selectionCheck: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: c.accent,
      alignItems: "center",
      justifyContent: "center",
    },
    inputShell: {
      height: controlHeight,
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      gap: 12,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: g.controlRadius,
      backgroundColor: c.surface,
    },
    inputEmbedded: {
      height: controlHeight - 2,
      minHeight: 0,
      flex: 1,
      minWidth: 0,
      borderWidth: 0,
      paddingHorizontal: 0,
    },
    codeControl: { position: "relative" },
    codeCells: { flexDirection: "row", alignItems: "center", gap: 6 },
    codeCell: {
      flex: 1,
      minHeight: 54,
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: g.controlRadius,
      backgroundColor: c.surface,
      alignItems: "center",
      justifyContent: "center",
    },
    codeDigit: {
      fontFamily: "FragmentMono_400Regular",
      fontSize: 24,
      color: c.ink,
    },
    codeSeparator: { fontSize: 24, color: c.line },
    codeCapture: {
      ...StyleSheet.absoluteFillObject,
      opacity: 0.02,
      color: "transparent",
      fontSize: 24,
    },
    controlFocused: {
      borderColor: c.accent,
      outlineWidth: 3,
      outlineColor: c.tint,
      outlineStyle: "solid",
    },
    stepIndicator: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
    },
    stepDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: c.line },
    stepDotActive: { width: 20, backgroundColor: c.accent },
    centeredRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
    },
    navigation: {
      width: compact ? 64 : 200,
      backgroundColor: c.side,
      borderRightWidth: 1,
      borderColor: c.divider,
      padding: compact ? 10 : 12,
      paddingTop: g.workspaceInset,
      gap: 8,
    },
    brand: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      minHeight: controlHeight,
    },
    identity: {
      flexDirection: "row",
      alignItems: "center",
      minHeight: 36,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.divider,
      borderRadius: g.controlRadius,
      paddingHorizontal: 8,
      gap: 8,
    },
    tileAvailable: { backgroundColor: c.hover },
    segments: {
      alignSelf: wide ? "flex-start" : "stretch",
      flexDirection: "row",
      backgroundColor: c.hover,
      borderRadius: g.controlRadius,
      padding: 3,
      gap: 2,
    },
    segment: {
      flex: wide ? 0 : 1,
      paddingHorizontal: wide ? 12 : 0,
      minHeight: 38,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: g.segmentRadius,
    },
    segmentText: { color: c.soft },
    segmentTextSelected: { color: c.ink },
    segmentSelected: {
      backgroundColor: c.surface,
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 2,
      elevation: 1,
    },
    navItem: {
      minHeight: g.touchHeight,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 12,
      borderRadius: g.controlRadius,
    },
    compactNav: { paddingHorizontal: 0, justifyContent: "center" },
    compactBrand: { justifyContent: "center" },
    navLabel: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchCaptionFont,
      lineHeight: g.touchControlLine,
      color: c.ink,
    },
    navSelected: { backgroundColor: c.tint },
    navFooter: { marginTop: "auto", padding: 12, gap: 6 },
    folderRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      minHeight: g.touchControlHeight + 2 * g.listRowPaddingY + 2,
      paddingVertical: g.listRowPaddingY,
      paddingHorizontal: g.listRowPaddingX,
      borderRadius: g.controlRadius,
    },
    groupedFolderRow: { backgroundColor: c.surface, borderRadius: 0 },
    actionRow: {
      flexDirection: "row",
      alignItems: "center",
      minHeight: 52,
      paddingVertical: 12,
      paddingHorizontal: 16,
      gap: 12,
    },
    deletedFile: { textDecorationLine: "line-through" },
    conflictChoice: { borderWidth: 2, borderColor: c.divider, gap: 8 },
    conflictChoiceSelected: { borderColor: c.accent },
    actionGroup: { overflow: "hidden" },
    destructiveActionGroup: { borderTopWidth: 1, borderColor: c.divider },
    sheetHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingHorizontal: wide ? 24 : 16,
      paddingTop: 12,
    },
    iconButton: { width: 44, paddingHorizontal: 0 },
    badgeWarning: { backgroundColor: c.warningBg },
    badgeWarningText: { color: c.warning },
    badgeError: { backgroundColor: c.dangerBg },
    badgeNeutral: { backgroundColor: c.hover },
    badgeNeutralText: { color: c.soft },
    noticeDock: {
      position: "absolute",
      left: n.inset,
      right: n.inset,
      alignItems: "center",
    },
    noticeStackScroll: { width: "100%", maxWidth: n.width, flexGrow: 0 },
    noticeStack: { gap: n.gap },
    noticeCard: {
      backgroundColor: c.noticeSurface,
      borderWidth: 1,
      borderColor: c.divider,
      borderRadius: n.radius,
      overflow: "hidden",
      shadowColor: "#000",
      shadowOpacity: 0.14,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    noticeInfo: {
      backgroundColor: c.noticeInfoBg,
      borderColor: c.noticeInfoBg,
    },
    noticeMain: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: n.gap,
      padding: n.padding,
    },
    noticeTitle: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: n.title,
      lineHeight: n.line,
      color: c.ink,
    },
    noticeText: {
      fontFamily: "InstrumentSans_400Regular",
      fontSize: n.body,
      lineHeight: n.line,
      color: c.soft,
      marginTop: 3,
    },
    noticeInfoText: { color: c.noticeInfoFg },
    noticeInfoLink: { color: c.noticeInfoLink },
    noticeMuted: { color: c.mute },
    noticeActions: {
      flexDirection: "row",
      gap: n.gap,
      flexWrap: "wrap",
      marginTop: 4,
    },
    noticeLink: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: n.body,
      lineHeight: n.line,
      color: c.noticeLink,
    },
    noticeLinkTarget: { minHeight: g.touchHeight, justifyContent: "center" },
    noticeClose: {
      width: 16,
      height: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    noticeDetails: {
      backgroundColor: c.paper,
      borderTopWidth: 1,
      borderColor: c.divider,
    },
    noticeDetailsHead: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: n.padding,
    },
    noticeDetailsToggle: {
      flex: 1,
      flexDirection: "row",
      gap: 8,
      minHeight: g.touchHeight,
      alignItems: "center",
    },
    noticeDetailsLabel: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: 13,
      color: c.soft,
    },
    noticeTraceScroll: { maxHeight: 180 },
    noticeTrace: {
      fontFamily: "FragmentMono_400Regular",
      fontSize: 12,
      lineHeight: 18,
      color: c.soft,
      paddingHorizontal: n.padding,
      paddingBottom: n.padding,
    },
    connectionCard: {
      borderRadius: g.controlRadius,
      paddingVertical: 12,
      paddingHorizontal: 14,
    },
    machineRow: {
      borderRadius: g.cardRadius,
      paddingVertical: wide ? 14 : 12,
      paddingHorizontal: 16,
    },
    machineTile: {
      width: wide ? 40 : 32,
      height: wide ? 40 : 32,
      borderRadius: g.controlRadius,
    },
    hubTile: { backgroundColor: c.accent },
    hubTag: { backgroundColor: c.accent, borderColor: c.accent },
    machineEnd: { alignItems: "flex-end", gap: 6 },
    machineIdentity: { flexDirection: "row", alignItems: "center", gap: 6 },
    machineName: { flexShrink: 1 },
    machineTag: {
      height: g.tagHeight,
      justifyContent: "center",
      alignSelf: "center",
      borderWidth: 1,
      borderColor: c.divider,
      borderRadius: g.tagRadius,
      paddingHorizontal: g.tagX,
      paddingVertical: g.tagY,
    },
    machineTagText: {
      textTransform: "uppercase",
      fontFamily: "FragmentMono_400Regular",
      fontSize: g.tagFont,
      lineHeight: g.tagLine,
      includeFontPadding: false,
      color: c.ink,
    },
    hubTagText: { color: c.onAccent },
    selfTagText: { color: c.okFg },
    selfTag: { backgroundColor: c.tint, borderColor: "transparent" },
    statDivider: { borderLeftWidth: 1, borderLeftColor: c.divider },
    statValue: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: 20,
      lineHeight: 26,
      color: c.ink,
    },
    statsGrid: { flexDirection: "row", flexWrap: "wrap" },
    statCell: { width: wide ? "25%" : "50%", padding: 12, gap: 6 },
    detailGrid: { flexDirection: wide ? "row" : "column", gap: 16 },
    detailMain: { flex: wide ? 1 : undefined, minWidth: 0, gap: 12 },
    detailSide: {
      width: wide ? g.detailSideWidth : undefined,
      flexShrink: 0,
      minWidth: 0,
      gap: 12,
    },
    folderToolbar: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
    },
    folderTools: { gap: 12 },
    historyTools: { flexDirection: "row", alignItems: "center", gap: 8 },
    historyFolderFilter: { width: wide ? 140 : undefined },
    historyGroups: { gap: 24 },
    historyFolder: { width: 110 },
    historyRevision: { width: 64 },
    historyDate: { width: 90 },
    rowAction: { flexDirection: "row", alignItems: "center", gap: 12 },
    compactActions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    rowTitle: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchRowFont,
      lineHeight: g.touchRowLine,
      color: c.ink,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(18,26,22,0.32)",
      justifyContent: wide ? "center" : "flex-end",
      alignItems: "center",
      padding: wide ? 24 : 0,
    },
    sheetScroll: { flexShrink: 1 },
    modalPanel: {
      flexShrink: 1,
      width: "100%",
      maxWidth: wide ? 600 : undefined,
      maxHeight: "95%",
      backgroundColor: c.paper,
      borderRadius: 14,
      overflow: "hidden",
    },
    dangerCard: { borderColor: c.danger },
    destructivePrimary: { backgroundColor: c.danger, borderColor: c.danger },
    dangerButton: { borderColor: c.danger },
    quietButton: {
      flexShrink: 0,
      borderWidth: 0,
      backgroundColor: "transparent",
      paddingHorizontal: 0,
      alignSelf: "flex-start",
    },
    switchTarget: {
      minWidth: 44,
      minHeight: g.touchHeight,
      alignItems: "center",
      justifyContent: "center",
    },
    switchTrack: {
      width: 40,
      height: 24,
      borderRadius: g.cardRadius,
      padding: 3,
      backgroundColor: c.line,
    },
    switchOn: { backgroundColor: c.accent },
    switchThumb: {
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: "#ffffff",
    },
    switchThumbOn: { alignSelf: "flex-end" },
    centerText: { textAlign: "center" },
    scroll: { flex: 1 },
    viewHeader: {
      padding: wide ? g.workspaceInset : 16,
      paddingBottom: g.headerBottomGap,
      gap: 16,
      backgroundColor: c.paper,
      width: "100%",
      maxWidth: 1400,
      alignSelf: "center",
    },
    viewBody: { paddingTop: 0 },
    content: {
      padding: wide ? g.workspaceInset : 16,
      gap: g.sectionGap,
      width: "100%",
      maxWidth: 1400,
      alignSelf: "center",
      flexGrow: 1,
    },
    screenHeader: { minHeight: controlHeight },
    screenTitle: { flexDirection: "row", alignItems: "center", gap: 12 },
    title: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: wide ? g.desktopTitleFont : g.touchTitleFont,
      lineHeight: wide ? g.desktopTitleLine : g.touchTitleLine,
      color: c.ink,
      letterSpacing: -0.5,
    },
    heading: {
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchRowFont,
      lineHeight: g.touchRowLine,
      color: c.ink,
    },
    text: {
      fontFamily: "InstrumentSans_400Regular",
      fontSize: g.touchBodyFont,
      lineHeight: g.touchBodyLine,
      color: c.soft,
    },
    caption: {
      fontFamily: "InstrumentSans_400Regular",
      fontSize: g.touchCaptionFont,
      color: c.soft,
      lineHeight: g.touchCaptionLine,
    },
    eyebrow: {
      fontFamily: "FragmentMono_400Regular",
      fontSize: 12,
      lineHeight: 18,
      color: c.mute,
      letterSpacing: 1,
    },
    mono: {
      fontFamily: "FragmentMono_400Regular",
      fontSize: 12,
      lineHeight: 18,
      color: c.soft,
    },
    row: { flexDirection: "row", alignItems: "center", gap: 12 },
    flex: { flex: 1, minWidth: 0 },
    stack: { gap: 4 },
    section: { gap: g.sectionLabelGap },
    group: {
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.divider,
      borderRadius: g.controlRadius,
      overflow: "hidden",
    },
    explorerEmpty: {
      alignItems: "center",
      paddingVertical: 48,
      paddingHorizontal: 20,
      gap: 8,
    },
    settingRow: {
      paddingHorizontal: wide ? 14 : 16,
      paddingVertical: wide ? 10 : 16,
      gap: 8,
    },
    breadcrumb: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 14,
      minHeight: 44,
    },
    breadcrumbButton: { minHeight: 44, justifyContent: "center" },
    separator: { borderTopWidth: 1, borderColor: c.divider },
    card: {
      backgroundColor: c.surface,
      borderColor: c.divider,
      borderWidth: 1,
      borderRadius: g.cardRadius,
      padding: 16,
      gap: 12,
    },
    available: {
      borderStyle: "dashed",
      borderColor: c.line,
      backgroundColor: c.paper,
    },
    tile: {
      width: 32,
      height: 32,
      borderRadius: g.controlRadius,
      backgroundColor: c.tint,
      alignItems: "center",
      justifyContent: "center",
    },
    button: {
      backgroundColor: c.surface,
      minHeight: g.touchControlHeight,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: g.controlRadius,
      borderWidth: 1,
      borderColor: c.line,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 8,
    },
    primary: { backgroundColor: c.accent, borderColor: c.accent },
    buttonLabel: {
      flexShrink: 0,
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.touchControlFont,
      lineHeight: g.touchControlLine,
      color: c.ink,
    },
    primaryLabel: { color: c.onAccent },
    disabled: { opacity: 0.5 },
    input: {
      height: controlHeight,
      minHeight: controlHeight,
      includeFontPadding: false,
      textAlignVertical: "center",
      borderWidth: 1,
      borderColor: c.line,
      borderRadius: g.controlRadius,
      paddingHorizontal: wide ? 12 : 16,
      paddingVertical: 0,
      backgroundColor: c.surface,
      color: c.ink,
      fontFamily: "InstrumentSans_400Regular",
      fontSize: g.touchInputFont,
      lineHeight: g.touchInputLine,
    },
    code: {
      fontFamily: "FragmentMono_400Regular",
      fontSize: 25,
      letterSpacing: 8,
      textAlign: "center",
    },
    tabs: {
      flexDirection: "row",
      borderTopWidth: 1,
      borderColor: c.divider,
      backgroundColor: c.paper,
      paddingTop: 8,
      paddingHorizontal: 8,
      paddingBottom: 4,
      gap: 4,
    },
    tab: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 5,
      minHeight: 60,
      paddingVertical: 6,
      borderRadius: g.controlRadius,
    },
    tabSelectedLabel: { fontFamily: "InstrumentSans_600SemiBold" },
    active: { color: c.accent },
    error: { backgroundColor: c.dangerBg, borderColor: c.danger },
    errorText: { color: c.danger },
    center: { alignItems: "center", gap: 16, paddingVertical: 26 },
    logo: { width: 76, height: 76 },
    folderList: { gap: g.listItemGap },
    badge: {
      flexDirection: "row",
      alignItems: "center",
      gap: g.pillGap,
      backgroundColor: c.tint,
      borderRadius: g.pillRadius,
      paddingLeft: g.pillLeft,
      paddingRight: g.pillRight,
      paddingVertical: g.pillY,
      alignSelf: "flex-start",
    },
    badgeText: {
      color: c.okFg,
      fontFamily: "InstrumentSans_600SemiBold",
      fontSize: g.pillFont,
      lineHeight: g.pillLine,
      includeFontPadding: false,
    },
  });
}
