import fs from "node:fs";
import { fileURLToPath } from "node:url";
import { palettes } from "../apps/mobile/src/palette.js";
import { geometry } from "../apps/mobile/src/design-tokens.js";

const kebab = (name) => name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
const unitless = new Set(["iconStroke"]);
const declare = (entries) =>
  entries
    .map(
      ([name, value]) =>
        `  --m-${kebab(name)}: ${typeof value === "number" && !unitless.has(name) ? `${value}px` : value};`,
    )
    .join("\n");

export function mobileTokens() {
  return `/* Generated by design/build.js from apps/mobile/src/palette.js and design-tokens.js; do not edit. */
:root {
${declare(Object.entries(palettes.light))}
${declare(Object.entries(geometry))}
}
[data-theme="dark"] {
${declare(Object.entries(palettes.dark))}
}
`;
}

const iconSource = new URL(
  "../apps/desktop/src/assets/arca-icon.svg",
  import.meta.url,
);
const outputs = () => [
  [new URL("./mobile-tokens.css", import.meta.url), mobileTokens()],
  [new URL("./favicon.svg", import.meta.url), fs.readFileSync(iconSource)],
];

export function stale() {
  return outputs()
    .filter(([file, content]) => {
      try {
        return !fs.readFileSync(file).equals(Buffer.from(content));
      } catch {
        return true;
      }
    })
    .map(([file]) => fileURLToPath(file));
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  if (process.argv.includes("--check")) {
    const behind = stale();
    if (behind.length) {
      console.error(`stale: ${behind.join(", ")}; run \`npm run design\``);
      process.exit(1);
    }
  } else {
    for (const [file, content] of outputs()) fs.writeFileSync(file, content);
  }
}
