import fs from "node:fs";
import { fileURLToPath } from "node:url";
import { palettes } from "../apps/mobile/src/palette.js";
import { geometry } from "../apps/mobile/src/design-tokens.js";

const kebab = (name) => name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
const unitless = new Set(["iconStroke"]);
const declare = (entries) =>
  entries
    .map(
      ([name, value]) =>
        `  --m-${kebab(name)}: ${typeof value === "number" && !unitless.has(name) ? `${value}px` : value};`,
    )
    .join("\n");

export function mobileTokens() {
  return `/* Generated by scripts/design-tokens.js from apps/mobile/src/palette.js and design-tokens.js; do not edit. */
:root {
${declare(Object.entries(palettes.light))}
${declare(Object.entries(geometry))}
}
[data-theme="dark"] {
${declare(Object.entries(palettes.dark))}
}
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url))
  fs.writeFileSync(
    new URL("../design/mobile-tokens.css", import.meta.url),
    mobileTokens(),
  );
